[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 8080
  publish = "dist"
  autoLaunch = true

# Redirect API calls to the Netlify function
[[redirects]]
  from = "/api/samurai-v2"
  to = "/.netlify/functions/samurai-v2"
  status = 200
  force = true

# Redirect for Groq prompt enhancement function
[[redirects]]
  from = "/api/enhance-prompt-groq"
  to = "/.netlify/functions/enhance-prompt-groq"
  status = 200
  force = true

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 